### ISSUE TITLE
fanotaur crash

### ISSUE THREAD

**Issue by gordan-bobic** [m4rkw/gpustatd#11]
```
$ DISPLAY=:10 nvidia-settings -q '[fan:1]/GPUTargetFanSpeed'

  Attribute 'GPUTargetFanSpeed' (normandy.shatteredsilicon.net:10[fan:1]): 80.
    The valid values for 'GPUTargetFanSpeed' are in the range 0 - 100 (inclusive).
    'GPUTargetFanSpeed' can use the following target types: Fan.

-bash-4.2$ fanotaur
info: fanotaur 0.8.5 starting up
info: scanning devices
info: self-test
info: looks good, monitoring
Traceback (most recent call last):
  File "/home/mock/rpmbuild/BUILD/fanotaur-0.8.5/fanotaur.py", line 162, in <module>
  File "/home/mock/rpmbuild/BUILD/fanotaur-0.8.5/fanotaur.py", line 34, in __init__
  File "/home/mock/rpmbuild/BUILD/fanotaur-0.8.5/fanotaur.py", line 71, in self_test
  File "/home/mock/rpmbuild/BUILD/fanotaur-0.8.5/fanotaur.py", line 108, in start
  File "/home/mock/rpmbuild/BUILD/fanotaur-0.8.5/fanotaur.py", line 129, in check_fan_state
  File "/home/mock/rpmbuild/BUILD/fanotaur-0.8.5/nvidia.py", line 62, in get_fan_control_state
Exception: failed to query fan control state for device: 1
```

**Comment by m4rkw** [comment]
try gpustatd, fanotaur is EOL :)

**Comment by m4rkw** [comment]
also fan control state isn't the same thing as fan speed, try running with debug: true
